server:
  port: 8080
  reactive:
    session:
      cookie:
        path: "/"
        max-age: 31536000
        domain: localhost
        secure: true
        http-only: true
        same-site: none

logging:
  level:
    root: info
    org.hibernate.envers.boot: OFF

spring:
  jpa:
    database: mysql
    open-in-view: false
    properties:
      hibernate.id.new_generator_mappings: false
      hibernate.implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      hibernate.physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      hibernate.globally_quoted_identifiers: true
      hibernate.globally_quoted_identifiers_skip_column_definitions: true
      hibernate.default_batch_fetch_size: 500
      org:
        hibernate:
          envers:
            revision_field_name: revision_id
            revision_type_field_name: revision_type
            audit_table_suffix: _histories
            store_data_at_delete: true
      hibernate:
        show_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/scrimmers
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  flyway:
    enabled: true
    baseline-version: 0
    out-of-order: true

jwt:
  issuer: ENC(e1Aco7xX3BcNC142nLMG5Mi9qBkR2chRK7Pj6AMmdEft+ZpeavpsUNz1H5CE0VuO)
  secret: ENC(4b2Jr2fE0xxQap9Yn0osoRWrSx+9N6KbEwRHuxWTUH8AbNjy1PeJEYjPZynMw8xO)

jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA512ANDAES_256
    key-obtention-iterations: 1000
    pool-size: 1
    provider-name: SunJCE
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
    string-output-type: base64

redis:
  chobolevel:
    host: localhost
    port: 6379
    password:
