server:
  port: 9280
  reactive:
    session:
      cookie:
        path: "/"
        max-age: 31536000
        domain: ENC(sS58ZgtLL1Ce9e8GM8fx9Oawdb65MCNS2cdyzK63bWtmvTqJeQfRLou2i7lxczWE)
        secure: true
        http-only: true
        same-site: none

logging:
  level:
    root: info
    org.hibernate.envers.boot: OFF
  config: classpath:logback-spring.xml

spring:
  application:
    name: diary
  jpa:
    database: mysql
    open-in-view: false
    databse-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate.id.new_generator_mappings: false
      hibernate.implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      hibernate.physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      hibernate.globally_quoted_identifiers: true
      hibernate.globally_quoted_identifiers_skip_column_definitions: true
      hibernate.default_batch_fetch_size: 1000
      org:
        hibernate:
          envers:
            revision_field_name: revision_id
            revision_type_field_name: revision_type
            audit_table_suffix: _histories
            store_data_at_delete: true
      hibernate:
        show_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: ENC(M8RnDICFlnvqiuERLBkaE5PiJzUmRXt1Mf5b+gIiH7KMOCWOxko+LwnhL1+cfBGjJuGa4zjp/J7+y76e66zBbV7AJBwxdWBrYZxsvpiYHPg=)
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(/C8HxWtU1KbvhopxrAJn//CIimnUJ32VBmitPGXCAn8fBSx7Z8gDcRUm+BO3Y0yC)
    password: ENC(j6cisZ5YuSmW70OIkjNxUf/FLCEmmH0Pz3XHCLPIx51GC/WhW24k3XDEQtsuoLwk)
  flyway:
    enabled: true
    baseline-version: 0
    out-of-order: true
  data:
    redis:
      host: ENC(sS58ZgtLL1Ce9e8GM8fx9Oawdb65MCNS2cdyzK63bWtmvTqJeQfRLou2i7lxczWE)
      port: 6379
      password:

# jasypt config
jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA512ANDAES_256
    key-obtention-iterations: 1000
    pool-size: 1
    provider-name: SunJCE
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
    string-output-type: base64

jwt:
  issuer: ENC(IrVcIRyI9zo//V57Nsm8uwLDgHSEYXh5bUECfMUiwi+RvfUVw7TK8LvKR/L1b25b)
  secret: ENC(iPH58HCZPwX+hn4CAE1jVLic1yqdoZEd8H1nNaRL9I+RjMHIbkiQHfMtaGBbyPK3AkH2k84jQQctcFqNQHwjjUbghieFOpXjc2rKfhZ4gvI=)
  access-token-key: ENC(oyacngno8S+O91nE9wCzqUCnEVORn3GU4zMWIASRLI9P8oqLMM2JznCTvcLJaLiA)
  refresh-token-key: ENC(UtZGrx5mKW5E1bRippO+bAHR/P252MMqmE5kTASYNMjJ5pEQPShToqoGYGK8XVQj)
  refresh-token-cache-key: ENC(jrDKzvR+c0B+RIebZLJUxiH6EKKcvU506aMIHr6QsLw2nQ5WSCoO2Y2EzkWyOG051bi16RkFLbizC84ryEZkWA==)

cloud:
  aws:
    s3:
      bucket: ENC(mY/nEChyl+2UkJ+6ksyBpsrxAdPfllCiLsQRfeTkbYlx8HF9BzoWQTKsD2qtix3F)
    stack.auto: false
    region.static: ENC(MGnH9MBS4YmcD5OiFlPXo54LIbzK9P6uGb4Z/JA/aIBJ4bnqcus6VslMKtvGfbzb)
    credentials:
      accessKey: ENC(S+dLvOJNzvqPqxvcaJYNIo4X9yuQ7G6WQaFZZxwX++zcTuAdf6lpwxlyDSu1GF68yqbvYPIlc++f+G7TD5K7tQ==)
      secretKey: ENC(xxBozMXFLkVLXx7YJoa2ViB2K2trsZ6dm4oUKrtHriUUUrq+I2TGWZMKI5sFVQ6YY5VxL+2b3Kt+hCeJkHN7bQNaHI+CJABGeLJBrU3rgiU=)
